### ISSUE TITLE
Support previous visual studio versions 

### ISSUE THREAD

**Issue by clmcgrath** [Microsoft/vssetup.powershell#28]
Add support to locate legacy versions of visual studio  
vswhere has support for this via -legacy

**Comment by heaths** [comment]
Older installs do not support anywhere close to the amount of information these cmdlets are meant to expose. See issue #12. If you want to find older versions, use https://github.com/Microosft/vswhere. These cmdlets are for Visual Studio 2017 and newer because that what the query API on which they are built are bound to.
