### ISSUE TITLE
Cannot Remove-Module since VSSetupVersionTable is constant

### ISSUE THREAD

**Issue by heaths** [Microsoft/vssetup.powershell#47]
Apparently never tested just removing the VSSetup module. One cannot since `$VSSetupVersionTable` is constant, nor can it be forcibly removed. Should make it read-only. Seems there'd be little incentive to change the values and `$PSVersionTable` doesn't prevent it either. Should also probably set the `AllScope` option as is set on `$PSVersionTable`.

**Comment by mide1234** [comment]
I guess it is related but I am not an expert in this area. When importing the VSSetup module one can see the following exception:

**Import-Module VSSetup [<<==>>] Exception: Cannot overwrite variable VSSetupVersionTable because it is read-only or constant.**

The VSSetup is installed on a an environment where it might be already installed via the following code:
```powershell
# User has to exit the current session after installing the latest version of PowerShellGet. - https://github.com/PowerShell/PowerShellGet/issues/227
PowerShell -Command {
	# VSSetup requires PSGet to be installed https://docs.microsoft.com/en-us/powershell/gallery/installing-psget
	Write-Host "Installing NugetProvider for powershell"	
	Install-PackageProvider Nuget –Force;
	Write-Host "NugetProvider for powershell installed"
	
	Write-Host "Installing PowerShellGet"	
	Install-Module –Name PowerShellGet –Force;
	Write-Host "PowerShellGet installed"
	
	# VSSetup installation: https://github.com/Microsoft/vssetup.powershell
	Write-Host "Installing VSSetup"	
	Install-Module VSSetup -Scope CurrentUser -Force;
	Write-Host "VSSetup installed"
}
```

**Comment by SimonTaubertTCNE** [comment]
For us this has resulted in a total breakdown of the entire build and deploy process, since psake includes the line `Import-Module VSSetup` which throws `Exception: Cannot overwrite variable VSSetupVersionTable because it is read-only or constant.
Psake failed...`

**Comment by jwittner** [comment]
I've effectively abandoned use of version 2.2.0 because of this issue.

**Comment by pianomanjh** [comment]
Also struggling with our builds due to this issue.

**Comment by SimonTaubertTCNE** [comment]
I'm glad to see I'm not alone, but unfortunately I have no workaround as of yet. I got the build to pass once by manually commenting out the specified line i the psake code (ConfigureBuildEnvironment.ps1) on the build server.  But that of course gets run over when the build scripts fetches the psake nuget package next time... 

@jwittner: How do you mean "abandoned"? I can't see a way of choosing which version to use, or is there?

**Comment by mide1234** [comment]
@SimonTaubertTCNE My current workaround is a bit dummy, but basically removes all versions of VSSetup and installs the working one (prior to version 2.2.0) nad it works for me :)

```powershell
Uninstall-Module VSSetup -AllVersions -Force
Install-Module VSSetup -Scope CurrentUser -Force -MaximumVersion 2.0.1;
```

**Comment by SimonTaubertTCNE** [comment]
@mide1234 Ok, nice. But I guess there is a problem still since the Install command without the MaximumVersion flag is in the Psake source code. Or did you get that flow working?

**Comment by SimonTaubertTCNE** [comment]
@mide1234 That's how I understood it prior to this issue, but the exception thrown is from the psake source code:
https://github.com/psake/psake/blob/09713113ec9cef6f240e83147e549c62cf0a7f87/src/private/ConfigureBuildEnvironment.ps1#L100
(here on disk: \Packages\psake.4.7.0\tools\psake\private\ConfigureBuildEnvironment.ps1 line 99)

**Comment by SimonTaubertTCNE** [comment]
@mide1234 Your workaround did indeed save the day, thanks! 

One fix was needed though, the script, when run in a console window, prompted for a verification that the Powershell gallery was a trusted source. This made the process halt in an infinite loop when run from an automation server like Jenkins since it never got an answer. But this was solved by setting the installation policy once and for all manually first:
`Set-PSRepository -Name PSGallery -InstallationPolicy Trusted`

**Comment by mide1234** [comment]
@SimonTaubertTCNE You are welcome, I am glad you were able to fix your build :)
