### ISSUE TITLE
Support for querying installation status of packages

### ISSUE THREAD

**Issue by mathstuf** [Microsoft/vssetup.powershell#84]
I can get a list of *all* packages with this pipeline:

```powershell
Get-VSSetupInstance | Select-VSSetupInstance -Product * | ConvertTo-Json
```

But I don't see anything in this output that indicates which of the `Packages` array entries are already installed. I can get it from the installer by exporting a `.vsconfig` file with the list of installed components, but it'd be nice to have an automated way to do this.

FWIW, my plan is to support using Ansible to control the list of installed components and being able to detect what is there would be useful for adding/removing components.

**Comment by heaths** [comment]
Only installed packages are registered to the instance. You're querying the instance - not the catalog. So that is all your installed packages. See the wiki for some samples how to better format or query that.

**Comment by mathstuf** [comment]
Interesting. It's not clear to me how that works…I guess the strings repr in the plain `Select-VSSetupInstance` hides additional information that ends up allowing filtering. The pipeline I have has 1000+ packages listed, but the wiki's example shows a few dozen. Anyways, that gets me further, thanks.

**Comment by heaths** [comment]
VS2019 and newer (and more are added or refactored in newer versions) have thousands of small packages by design. It's a new, faster, more stable approach than previous versions' installer technology. Note that there are more properties on packages than what show by default. As with most cmdlets - especially those built-in - only a subset of properties are shown. `| select *` or `| gm` can show more.

Reading all packages available from a catalog isn't supported by this module, but is possible by downloading the catalog and using PowerShell's `ConvertFrom-Json`.
